AUDIO_ENABLE = no
TAP_DANCE_ENABLE = no
KEY_LOCK_ENABLE = no
AUTO_SHIFT_ENABLE = no
CAPS_WORD_ENABLE = no
SEND_STRING_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
# MOUSEKEY_ENABLE = no
# POINTING_DEVICE_ENABLE = no
CONSOLE_ENABLE = yes
# BOOTMAGIC_ENABLE = no
EXTRAKEY_ENABLE = yes
WPM_ENABLE = yes
# TERMINAL_ENABLE = yes


SRC += ddrcode.c
